project_id = "grjyybmjrzrurlzdqmqc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[auth.email]
enable_signup = true

[functions.send-org-invite]
verify_jwt = false

[functions.send-credit-alert]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-mood-nudge]
verify_jwt = false